name: Set environment variables
on: [push]
env:
    REACT_APP_API_KEY: ${{ secrets.API_KEY }}
    REACT_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
    REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
    REACT_APP_SENDER_ID: ${{ secrets.SENDER_ID }}
    REACT_APP_APP_ID: ${{ secrets.APP_ID }}

jobs:
  trying-to-use-environment-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          echo ${{ secrets.API_KEY }}
          echo "REACT_APP_API_KEY=${{ secrets.API_KEY }}"
          echo ${{ secrets.AUTH_DOMAIN }}
          echo "REACT_APP_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}"
          echo ${{ secrets.PROJECT_ID }}
          echo "REACT_APP_PROJECT_ID=${{ secrets.PROJECT_ID }}"
          echo ${{ secrets.STORAGE_BUCKET }}
          echo "REACT_APP_STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}"
          
          echo ${{ secrets.SENDER_ID }}
          echo "REACT_APP_SENDER_ID=${{ secrets.SENDER_ID }}"
          echo ${{ secrets.APP_ID }}
          echo "REACT_APP_APP_ID=${{ secrets.APP_ID }}"
